[project]
name = "whatsapp-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp<3",
    "httpx>=0.28.1",
    "requests>=2.32.3",
]
